### ISSUE TITLE
gen_raw_from_broadlink error.

### ISSUE THREAD

**Issue by TiagoBarata** [elupus/irgen#2]
Hi,

I'm trying to get the raw or pronto codes from the broadlink base64 code:

data = b"JgCSAAABJ5UUFBQUExQUOBQUFBMUFBQUFDgUExQUFDgUExQUFBQUExQUFBQUExQUFBQUOBM4FBQUFBQTFBQUFBQ4FBMUOBQUFBMUOBQUFAACkhUTFDgUFBQTFBQUFBQTFBQUOBQUExQUFBQTFDgUFBQUFBMUFBQUFBMUFBQUFBMUFBQUFBMUFBQUFDcUFBQ4FDgUAA0FAAAAAAAA"
raw  = list(irgen.gen_raw_from_broadlink_base64(data))

And i'm getting the error:

Traceback (most recent call last):
  File "C:\Users\Tiago\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Tiago\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\Tiago\.vscode\extensions\ms-python.python-2020.3.69010\pythonFiles\lib\python\debugpy\wheels\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\Tiago\.vscode\extensions\ms-python.python-2020.3.69010\pythonFiles\lib\python\debugpy\wheels\debugpy/..\debugpy\server\cli.py", line 427, in main
    run()
  File "c:\Users\Tiago\.vscode\extensions\ms-python.python-2020.3.69010\pythonFiles\lib\python\debugpy\wheels\debugpy/..\debugpy\server\cli.py", line 264, in run_file
    runpy.run_path(options.target, run_name="__main__")
  File "C:\Users\Tiago\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\Tiago\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Tiago\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\Tiago\OneDrive\3.Trabalho\3.PersonalProjects\Python\IRGenProj\Main.py", line 6, in <module>
    raw  = list(irgen.gen_raw_from_broadlink_base64(data))
  File "c:\Users\Tiago\OneDrive\3.Trabalho\3.PersonalProjects\Python\IRGenProj\.venv\lib\site-packages\irgen\__init__.py", line 246, in gen_raw_from_broadlink_base64
    yield from gen_raw_from_broadlink(b64decode(data))
  File "c:\Users\Tiago\OneDrive\3.Trabalho\3.PersonalProjects\Python\IRGenProj\.venv\lib\site-packages\irgen\__init__.py", line 237, in gen_raw_from_broadlink
    assert next(v) == 0x0d
AssertionError

Can you help?

Thank you

**Comment by TiagoBarata** [comment]
Got it working by commented the lines:
#assert next(v) == 0x0d
#assert next(v) == 0x05

**Comment by elupus** [comment]
Will change those to warning I think. The broadlink data should end with that. But perhaps something is stripping it.

**Comment by TiagoBarata** [comment]
And I had to change lines in:
  def gen_broadlink_from_raw(data, repeat=0):
  from:
    yield from b'\x0d'
    yield from b'\x05'
    
  to:
    yield from b'\x00'
    yield from b'\x00'

**Comment by whc2001** [comment]
The length is all the data after the length, including the 0D05 part. Change the `length` on line 235 to `length - 2` seems to fix this issue.

**Comment by elupus** [comment]
Ah. Yea that might be the case.
